# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

flavors = ["blueberry", "strawberry", "raspberry"]

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    gradle(task: "clean assembleRelease")
    crashlytics
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end

  desc "Fetch all metadata of apps"
  lane :fetchMetadata do
    flavors.each { |flavor|
        sh("fastlane supply init --metadata_path ./fastlane/metadata/" + flavor + " --package_name org.ea.multideploy." + flavor)
    }
  end

    desc "Upload to playstore"
    lane :playstore do
        flavors.each { |flavor|
            gradle(task: "clean")
            gradle(
                task: 'assemble' + flavor,
                build_type: 'Debug'
            )
            gradle(
                task: 'assemble' + flavor,
                build_type: 'DebugAndroidTest'
            )
            gradle(
                task: 'assemble' + flavor,
                build_type: 'Release'
            )
            capture_android_screenshots(
                app_package_name: 'org.ea.multideploy.' + flavor,
                clear_previous_screenshots: true,
                app_apk_path: "app/build/outputs/apk/" + flavor + "/debug/app-" + flavor + "-debug.apk",
                tests_apk_path: "app/build/outputs/apk/androidTest/" + flavor + "/debug/app-" + flavor + "-debug-androidTest.apk"
            )
            supply(
                track: 'internal',
                json_key: '/home/danielp/google-play-api.json',
                package_name: 'org.ea.multideploy.' + flavor,
                apk: "./app/build/outputs/apk/" + flavor + "/release/app-" + flavor + "-release.apk"
            )
        }
    end
end
